# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c17a2d0bd01dca94375fc711675893d1edb66544e0f69c499c36edad6ee967c31d6548106cc35ea22328c67e7dadedfba12f248b33f4ef5bdb1f550146e12e84

test:
  secret_key_base: a3f8509dbd7c25adef1f65c10088585fa2a0f373672e8d9d6311142fd875de7aa457f574428a87a369cada32e2c13bd3bb67dd6a5b7eb129cb7869c2f7e5f22e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
